controllers-films-users
KseniaYakovenko/java-filmorate pull request #5
Opened 2024-04-28 19:09 UTC by KseniaYakovenko

2024-04-29 13:33 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-04-29 13:33 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserRepository.java
> +        }
Можно инвертировать условный оператор и избавиться от `else`:

```java
if (oldUser == null) {
    throw new NotFoundException("Нет пользователя с id = " + id);
}
users.put(id, user);
```

2024-04-29 13:33 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmRepository filmRepository;
Не хватает модификаторов доступа

2024-04-29 13:33 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserRepository userRepository;
Не хватает модификаторов доступа

2024-04-29 13:33 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +public class FilmRepository {
Замечание аналогичное `UserRepository`

2024-04-29 20:07 UTC, KseniaYakovenko commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserRepository.java
> +        }
Спасибо, исправила

2024-04-29 20:08 UTC, KseniaYakovenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmRepository filmRepository;
добавила

2024-04-29 20:09 UTC, KseniaYakovenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserRepository userRepository;
добавила

2024-04-30 21:09 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-05-07 20:43 UTC, merged