sprint 11 - add friends likes
KseniaYakovenko/java-filmorate pull request #6
Opened 2024-05-10 18:10 UTC by KseniaYakovenko

2024-05-11 22:27 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара небольших замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-11 22:27 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorResponse.java
> +@RequiredArgsConstructor
Стоит воспользоваться аннотацией `@Data`, она включает в себя все эти аннотации

2024-05-11 22:27 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void addLike(@PathVariable long filmId, @PathVariable long userId) {
Либо везде используем модификаторы доступа (рекоммендую), либо везде игнорируем, не стоит смешивать это

2024-05-11 22:27 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping("/{userId}/friends/{friendId}")
Аналогично замечанию для `FilmController`

2024-05-12 09:26 UTC, KseniaYakovenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorResponse.java
> +@RequiredArgsConstructor
Спасибо, исправила

2024-05-12 09:26 UTC, KseniaYakovenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void addLike(@PathVariable long filmId, @PathVariable long userId) {
добавила

2024-05-12 09:26 UTC, KseniaYakovenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping("/{userId}/friends/{friendId}")
добавила

2024-05-13 07:14 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-05-27 21:00 UTC, merged